export const programOptions = [
    { value: "latest.academics.program_percentage.agriculture", label: "Agriculture, Agriculture Operations, And Related Sciences" },
    { value: "latest.academics.program_percentage.resources", label: "Natural Resources And Conservation" },
    { value: "latest.academics.program_percentage.architecture", label: "Architecture And Related Services" },
    { value: "latest.academics.program_percentage.ethnic_cultural_gender", label: "Area, Ethnic, Cultural, Gender, And Group Studies" },
    { value: "latest.academics.program_percentage.communication", label: "Communication, Journalism, And Related Programs" },
    { value: "latest.academics.program_percentage.communications_technology", label: "Communications Technologies/Technicians And Support Services" },
    { value: "latest.academics.program_percentage.computer", label: "Computer And Information Sciences And Support Services" },
    { value: "latest.academics.program_percentage.personal_culinary", label: "Personal And Culinary Services" },
    { value: "latest.academics.program_percentage.education", label: "Education" },
    { value: "latest.academics.program_percentage.engineering", label: "Engineering" },
    { value: "latest.academics.program_percentage.engineering_technology", label: "Engineering Technologies And Engineering-Related Fields" },
    { value: "latest.academics.program_percentage.language", label: "Foreign Languages, Literatures, And Linguistics" },
    { value: "latest.academics.program_percentage.family_consumer_science", label: "Family And Consumer Sciences/Human Sciences" },
    { value: "latest.academics.program_percentage.legal", label: "Legal Professions And Studies" },
    { value: "latest.academics.program_percentage.english", label: "English Language And Literature/Letters" },
    { value: "latest.academics.program_percentage.humanities", label: "Liberal Arts And Sciences, General Studies And Humanities" },
    { value: "latest.academics.program_percentage.library", label: "Library Science" },
    { value: "latest.academics.program_percentage.biological", label: "Biological And Biomedical Sciences" },
    { value: "latest.academics.program_percentage.mathematics", label: "Mathematics And Statistics" },
    { value: "latest.academics.program_percentage.military", label: "Military Technologies And Applied Sciences" },
    { value: "latest.academics.program_percentage.multidiscipline", label: "Multi/Interdisciplinary Studies" },
    { value: "latest.academics.program_percentage.parks_recreation_fitness", label: "Parks, Recreation, Leisure, And Fitness Studies" },
    { value: "latest.academics.program_percentage.philosophy_religious", label: "Philosophy And Religious Studies" },
    { value: "latest.academics.program_percentage.theology_religious_vocation", label: "Theology And Religious Vocations" },
    { value: "latest.academics.program_percentage.physical_science", label: "Physical Sciences" },
    { value: "latest.academics.program_percentage.science_technology", label: "Science Technologies/Technicians" },
    { value: "latest.academics.program_percentage.psychology", label: "Psychology" },
    { value: "latest.academics.program_percentage.security_law_enforcement", label: "Homeland Security, Law Enforcement, Firefighting And Related Protective Services" },
    { value: "latest.academics.program_percentage.public_administration_social_service", label: "Public Administration And Social Service Professions" },
    { value: "latest.academics.program_percentage.social_science", label: "Social Sciences" },
    { value: "latest.academics.program_percentage.construction", label: "Construction Trades" },
    { value: "latest.academics.program_percentage.mechanic_repair_technology", label: "Mechanic And Repair Technologies/Technicians" },
    { value: "latest.academics.program_percentage.precision_production", label: "Precision Production" },
    { value: "latest.academics.program_percentage.transportation", label: "Transportation And Materials Moving" },
    { value: "latest.academics.program_percentage.visual_performing", label: "Visual And Performing Arts" },
    { value: "latest.academics.program_percentage.health", label: "Health Professions And Related Programs" },
    { value: "latest.academics.program_percentage.business_marketing", label: "Business, Management, Marketing, And Related Support Services" },
    { value: "latest.academics.program_percentage.history", label: "History" },
];